#!/bin/bash

mvn clean test sonar:sonar \
  -Dsonar.projectKey=dsf7g789sdf6g76dfsg76dfh678dfg67df6 \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.login=e8f969c7aaf87a9724deb2c13d1c8387c5e49063